package com.tickatch.paymentservice.payment.domain.exception;

import io.github.tickatch.common.error.ErrorCode;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum PaymentErrorCode implements ErrorCode {
  INVALID_STATUS_FOR_SUCCESS(HttpStatus.BAD_REQUEST.value(), "INVALID_STATUS_FOR_SUCCESS"),
  INVALID_STATUS_FOR_CANCEL(HttpStatus.BAD_REQUEST.value(), "INVALID_STATUS_FOR_CANCEL"),
  INVALID_STATUS_FOR_FAIL(HttpStatus.BAD_REQUEST.value(), "INVALID_STATUS_FOR_FAIL"),
  INVALID_STATUS_FOR_REFUND(HttpStatus.BAD_REQUEST.value(), "INVALID_STATUS_FOR_REFUND"),
  INVALID_STATUS_FOR_REFUND_FAIL(HttpStatus.BAD_REQUEST.value(), "INVALID_STATUS_FOR_REFUND_FAIL"),
  INVALID_STATUS_FOR_EXPIRED(HttpStatus.BAD_REQUEST.value(), "INVALID_STATUS_FOR_EXPIRED"),
  INVALID_STATUS_FOR_PROCESSING(HttpStatus.BAD_REQUEST.value(), "INVALID_STATUS_FOR_PROCESSING"),
  INVALID_RESERVATION_FOR_PAYMENT(
      HttpStatus.BAD_REQUEST.value(), "INVALID_RESERVATION_FOR_PAYMENT"),

  NO_RESERVATION_LINK(HttpStatus.BAD_REQUEST.value(), "NO_RESERVATION_LINK"),
  INVALID_PAYMENT_PRICE(HttpStatus.BAD_REQUEST.value(), "INVALID_PAYMENT_PRICE"),
  INVALID_PAYMENT_METHOD(HttpStatus.BAD_REQUEST.value(), "INVALID_PAYMENT_METHOD"),
  DUPLICATE_RESERVATION_ID(HttpStatus.BAD_REQUEST.value(), "DUPLICATE_RESERVATION_ID"),
  RESERVATION_STATUS_CHANGE_FAILED(
      HttpStatus.BAD_REQUEST.value(), "RESERVATION_STATUS_CHANGE_FAILED"),

  PAYMENT_KEY_GENERATION_FAILED(HttpStatus.BAD_REQUEST.value(), "PAYMENT_KEY_GENERATION_FAILED"),
  PAYMENT_NOT_FOUND(HttpStatus.NOT_FOUND.value(), "PAYMENT_NOT_FOUND"),
  PAYMENT_CONFIRMATION_FAILED(HttpStatus.BAD_REQUEST.value(), "PAYMENT_CONFIRMATION_FAILED"),
  PAYMENT_CONFIRM_FAILED(HttpStatus.BAD_REQUEST.value(), "PAYMENT_CONFIRM_FAILED"),
  MULTIPLE_PAYMENT_FOUND(HttpStatus.BAD_REQUEST.value(), "MULTIPLE_PAYMENT_FOUND"),
  PAYMENT_KEY_NOT_FOUND(HttpStatus.NOT_FOUND.value(), "PAYMENT_KEY_NOT_FOUND"),

  PAYMENT_EVENT_PUBLISH_FAILED(
      HttpStatus.SERVICE_UNAVAILABLE.value(), "PAYMENT_EVENT_PUBLISH_FAILED"),

  INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR.value(), "INTERNAL_SERVER_ERROR"),
  ;

  private final int status;
  private final String code;
}
